version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27070:27017"

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  rede-social-app:
    image: israeldouglas25/rede-social-app:latest
    build: .
    container_name: rede-social-app
    ports:
      - "8082:8082"